server {
    listen 80;

    # 1. Все запросы, которые начинаются с /api/, отправляем в контейнер бэкенда
    location /api/ {
        proxy_pass http://backend:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Все остальные запросы (картинки, страницы) отдаем как обычный React-сайт
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
